package config

import (
	"bytes"
	"encoding/json"
	"flag"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

var update = flag.Bool("update", false, "rewrite docs/panel.schema.json and the reference table in docs/panel.md")

const (
	refBegin = "<!-- config-reference begin: generated by `go generate ./internal/panel/config`; do not edit -->\n"
	refEnd   = "<!-- config-reference end -->"
)

func docsPath(name string) string { return filepath.Join("..", "..", "..", "..", "docs", name) }

// The committed schema and reference table are what the Go types generate, so an
// editor validating against the schema and a reader of the table see the config
// the panel reads. `go generate ./internal/panel/config` rewrites both.
func TestGeneratedFilesAreCurrent(t *testing.T) {
	schema, err := jsonSchema()
	if err != nil {
		t.Fatal(err)
	}
	var probe map[string]any
	if err := json.Unmarshal(schema, &probe); err != nil || probe["additionalProperties"] != false {
		t.Fatalf("the generated schema must be JSON that refuses unknown keys: %v", err)
	}
	schemaPath := docsPath("panel.schema.json")
	md, err := os.ReadFile(docsPath("panel.md"))
	if err != nil {
		t.Fatal(err)
	}
	doc := string(md)
	i, j := strings.Index(doc, refBegin), strings.Index(doc, refEnd)
	if i < 0 || j < i {
		t.Fatalf("docs/panel.md has no generated reference between its markers (%q)", strings.TrimSpace(refBegin))
	}
	wantDoc := doc[:i+len(refBegin)] + referenceTable() + doc[j:]
	if *update {
		if err := os.WriteFile(schemaPath, schema, 0o644); err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(docsPath("panel.md"), []byte(wantDoc), 0o644); err != nil {
			t.Fatal(err)
		}
		return
	}
	got, err := os.ReadFile(schemaPath)
	if err != nil || string(got) != string(schema) {
		t.Errorf("docs/panel.schema.json is not what the config types generate (%v); run `go generate ./internal/panel/config`", err)
	}
	if doc != wantDoc {
		t.Errorf("the configuration reference in docs/panel.md is not what Fields generates; run `go generate ./internal/panel/config`")
	}
}

// The schema carries the validators' own patterns and the version gate.
func TestSchemaCarriesTheRules(t *testing.T) {
	b, err := jsonSchema()
	if err != nil {
		t.Fatal(err)
	}
	var s struct {
		Required   []string                   `json:"required"`
		Properties map[string]json.RawMessage `json:"properties"`
		AllOf      []struct {
			If struct {
				Properties struct {
					Version struct {
						Const int `json:"const"`
					} `json:"version"`
				} `json:"properties"`
			} `json:"if"`
			Then struct {
				Properties map[string]json.RawMessage `json:"properties"`
			} `json:"then"`
		} `json:"allOf"`
	}
	if err := json.Unmarshal(b, &s); err != nil {
		t.Fatal(err)
	}
	if len(s.Required) != 1 || s.Required[0] != "name" {
		t.Errorf("required %v", s.Required)
	}
	for key, re := range map[string]string{"tmux_socket": SocketNameRe.String(), "name": nameRe.String()} {
		if !strings.Contains(string(s.Properties[key]), `"pattern": "`+jsonQuote(re)+`"`) {
			t.Errorf("%s does not carry the validator's pattern %s: %s", key, re, s.Properties[key])
		}
	}
	if !strings.Contains(string(s.Properties["cards"]), `"pattern": "`+jsonQuote(refreshRe.String())+`"`) {
		t.Errorf("cards[].refresh does not carry the validator's pattern %s", refreshRe)
	}
	if len(s.AllOf) != 3 || s.AllOf[0].If.Properties.Version.Const != 1 || s.AllOf[1].If.Properties.Version.Const != 2 ||
		s.AllOf[2].If.Properties.Version.Const != 3 || string(s.AllOf[2].Then.Properties["metrics"]) != "false" {
		t.Fatalf("version gate %+v", s.AllOf)
	}
	v1, v2 := s.AllOf[0].Then.Properties, s.AllOf[1].Then.Properties
	for _, k := range []string{"templates", "queues", "alerts", "quota_guard", "host_names"} {
		if v, ok := v1[k]; !ok || string(v) != "false" {
			t.Errorf("version 1 does not ban %s", k)
		}
		if string(v2[k]) == "false" {
			t.Errorf("version 2 bans %s", k)
		}
	}
	// cards is version 1, and only its newer key is banned, inside its items.
	const pin = `{"items":{"properties":{"pin":false}}}`
	for v, props := range []map[string]json.RawMessage{v1, v2} {
		if got := compact(t, props["cards"]); got != pin {
			t.Errorf("version %d: cards gate %s, want %s", v+1, got, pin)
		}
	}
	const suggest = `{"items":{"properties":{"suggest":false}}}`
	if got := compact(t, v2["templates"]); got != suggest {
		t.Errorf("version 2: templates gate %s, want %s", got, suggest)
	}
}

func compact(t *testing.T, raw json.RawMessage) string {
	t.Helper()
	var b bytes.Buffer
	if err := json.Compact(&b, raw); err != nil {
		return "(" + err.Error() + ")"
	}
	return b.String()
}

func jsonQuote(s string) string {
	b, _ := json.Marshal(s)
	return strings.Trim(string(b), `"`)
}
