#!/bin/sh
# scaffold.sh [--dry-run] [--force]: put the operating model's PROJECT-OWNED files into the
# current git repository, from the clauductor plugin's scaffold/ directory. The /clauductor:init
# skill runs it.
#
# The plugin carries the framework (skills, agents, hooks, the workflow, the checks). What a
# project owns and edits (AGENTS.md, .claude/project.conf, model-roles.json, docs/, changes/,
# specs/, scripts/ci/, .clauductor/panel.json, .claude/settings.json) has to live in the
# repository, so this copies it there, and NEVER overwrites a file that exists:
#   - a file that exists is kept as it is, except these four, which are merged:
#       .gitignore             missing lines appended
#       .gitattributes         missing line-ending rules PREPENDED (the project's own lines win)
#       CLAUDE.md              `@AGENTS.md` appended when absent
#       .claude/settings.json  merged as `clauductor install` merges it (needs jq): the project's
#                              keys and values kept, missing keys added, the allow/deny lists and
#                              the sandbox's excluded commands and domains unioned, the status
#                              line the plugin's
#     and settings.json's gate paths follow GATE_RUN and GATE in .claude/project.conf.
#   - the repository is then marked with .claude/clauductor-plugin, which is what makes the
#     plugin's hooks act here (hooks/if-project.sh).
#
# THE GUARD (the same as `clauductor install`'s): a repository that runs an operating model of
# its own (AGENTS.md, .claude/skills, .claude/hooks or .claude/settings.json, and no marker) is
# refused unless --force, with the list of what would be added. A repository `clauductor install`
# set up (.claude/clauductor-template) is refused outright: run one or the other, not both.
#
# Generated by `clauductor plugin build` (framework/internal/plugin/assets). Plugin @VERSION@.
set -u
PLUGIN=$(cd "$(dirname "$0")" && pwd) || exit 1
SRC="$PLUGIN/scaffold"
dry=0
force=0
for a in "$@"; do
  case $a in
    --dry-run) dry=1 ;;
    --force) force=1 ;;
    *) echo "usage: scaffold.sh [--dry-run] [--force]" >&2; exit 2 ;;
  esac
done
ROOT=$(git rev-parse --show-toplevel 2>/dev/null) || {
  echo "REFUSED: $(pwd) is not in a git repository. Run git init first (the model lives in git: branches, worktrees, PRs)." >&2
  exit 1
}
cd "$ROOT" || exit 1

if [ -f .claude/clauductor-template ]; then
  echo "REFUSED: $ROOT has the operating model from \`clauductor install\` (.claude/clauductor-template)."
  echo "Run one or the other, not both: keep the installed copy and disable the plugin for this repository"
  echo "(\"enabledPlugins\": {\"clauductor@clauductor\": false} in .claude/settings.local.json), or remove the"
  echo "installed framework files and the marker, then run /clauductor:init again."
  exit 1
fi

files=$(cd "$SRC" && find . -type f | sed 's|^\./||' | LC_ALL=C sort)
create=""
keep=""
merge=""
for f in $files; do
  case $f in
    .gitignore | .gitattributes | CLAUDE.md | .claude/settings.json)
      if [ -e "$f" ]; then merge="$merge $f"; else create="$create $f"; fi ;;
    *)
      if [ -e "$f" ]; then keep="$keep $f"; else create="$create $f"; fi ;;
  esac
done

own=""
if [ ! -f .claude/clauductor-plugin ]; then
  for s in AGENTS.md .claude/skills .claude/hooks .claude/settings.json; do
    [ -e "$s" ] && own="$own $s"
  done
fi

list() { for x in $2; do echo "    $1 $x"; done; }
if [ -n "$own" ] && [ "$force" = 0 ]; then
  echo "REFUSED: $ROOT runs an operating model of its own (found:$own; no .claude/clauductor-plugin)."
  echo "Nothing is ever overwritten, but init would ADD these beside the project's own files:"
  list + "$create"
  [ -n "$merge" ] && { echo "and MERGE into:"; list '&' "$merge"; }
  echo "The panel needs none of this: \`clauductor panel\` works in any repository as it is. To add the"
  echo "model anyway, run again with --force (commit first)."
  exit 1
fi

echo "clauductor init in $ROOT (plugin @VERSION@)"
[ -n "$create" ] && { echo "  create:"; list + "$create"; }
[ -n "$merge" ] && { echo "  merge:"; list '&' "$merge"; }
[ -n "$keep" ] && { echo "  keep (exists, left as it is):"; list = "$keep"; }
if [ "$dry" = 1 ]; then
  echo "--dry-run: nothing written."
  exit 0
fi

for f in $create; do
  mkdir -p "$(dirname "$f")" && cp -p "$SRC/$f" "$f" || { echo "FAILED to create $f" >&2; exit 1; }
done

# render_settings: the scaffold's settings.json with the gate's paths (allow rules, sandbox
# exclusions) at the project's GATE_RUN and GATE, read from its project.conf in a subshell.
conf_get() { sh -c '[ -f .claude/project.conf ] && . ./.claude/project.conf >/dev/null 2>&1; eval "printf %s \"\${$1:-$2}\""' _ "$1" "$2"; }
render_settings() {
  if command -v jq >/dev/null 2>&1; then
    jq --arg r "$(conf_get GATE_RUN scripts/ci/run-local.sh)" --arg g "$(conf_get GATE scripts/ci/gate.sh)" '
      def rp: if type == "string" then (split("scripts/ci/run-local.sh") | join($r)) | (split("scripts/ci/gate.sh") | join($g)) else . end;
      (if .permissions.allow then .permissions.allow |= map(rp) else . end)
      | (if .sandbox.excludedCommands then .sandbox.excludedCommands |= map(rp) else . end)' "$SRC/.claude/settings.json"
  else
    cat "$SRC/.claude/settings.json"
  fi
}
case " $create " in
  *" .claude/settings.json "*) render_settings > .claude/settings.json.tmp && mv .claude/settings.json.tmp .claude/settings.json ;;
esac
for f in $merge; do
  case $f in
    .gitignore)
      added=0
      while IFS= read -r line; do
        case $line in "" | "#"*) continue ;; esac
        grep -qxF -- "$line" .gitignore || { [ "$added" = 1 ] || printf '\n# clauductor\n' >> .gitignore; printf '%s\n' "$line" >> .gitignore; added=1; }
      done < "$SRC/.gitignore" ;;
    .gitattributes)
      # PREPENDED, not appended: the last matching line wins, so the project's own lines must
      # stay after the catch-all `* text=auto eol=lf` to keep overriding it.
      missing=""
      while IFS= read -r line; do
        case $line in "" | "#"*) continue ;; esac
        grep -qxF -- "$line" .gitattributes || missing="$missing$line
"
      done < "$SRC/.gitattributes"
      if [ -n "$missing" ]; then
        { printf '# clauductor: LF line endings on every OS (checks/line-endings.sh). Your own lines below still win.\n%s\n' "$missing"; cat .gitattributes; } > .gitattributes.tmp &&
          mv .gitattributes.tmp .gitattributes
      fi ;;
    CLAUDE.md)
      grep -qxF '@AGENTS.md' CLAUDE.md || printf '\n@AGENTS.md\n' >> CLAUDE.md ;;
    .claude/settings.json)
      if command -v jq >/dev/null 2>&1 && jq -e . .claude/settings.json >/dev/null 2>&1; then
        render_settings > .claude/settings.json.want &&
        jq -s '.[0] as $have | .[1] as $want
          | def u($a; $b): ($a // []) + (($b // []) - ($a // []));
          ($want * $have)
          | .statusLine = $want.statusLine
          | .permissions.allow = u($have.permissions.allow; $want.permissions.allow)
          | .permissions.deny = u($have.permissions.deny; $want.permissions.deny)
          | .sandbox.excludedCommands = u($have.sandbox.excludedCommands; $want.sandbox.excludedCommands)
          | .sandbox.network.allowedDomains = u($have.sandbox.network.allowedDomains; $want.sandbox.network.allowedDomains)' \
          .claude/settings.json .claude/settings.json.want > .claude/settings.json.tmp &&
          mv .claude/settings.json.tmp .claude/settings.json
        rm -f .claude/settings.json.want
      else
        echo "  NOTE: .claude/settings.json kept as it is (no jq, or not valid JSON). Add by hand what"
        echo "        $SRC/.claude/settings.json sets: statusLine, permissions.allow, enabledPlugins."
      fi ;;
  esac
done
printf 'This repository runs the clauductor operating model from the clauductor plugin (@VERSION@ at init).\nThe plugin'"'"'s hooks act only where this file exists. Delete it to make them stand aside.\n' > .claude/clauductor-plugin
echo "  marked: .claude/clauductor-plugin"
echo "Next: /clauductor:start-project, then commit."
