#!/bin/sh
# scaffold.sh [--dry-run] [--force]: put the operating model's PROJECT-OWNED files into the
# current git repository, from the clauductor plugin's scaffold/ directory. The /clauductor:init
# skill runs it.
#
# The plugin carries the framework (skills, agents, hooks, the workflow, the checks). What a
# project owns and edits (AGENTS.md, .claude/project.conf, model-roles.json, docs/, changes/,
# specs/, scripts/ci/, .clauductor/panel.json, .claude/settings.json) has to live in the
# repository, so this copies it there, and NEVER overwrites a file that exists:
#   - a file that exists is kept as it is, except these three, which are merged:
#       .gitignore             missing lines appended
#       CLAUDE.md              `@AGENTS.md` appended when absent
#       .claude/settings.json  missing keys added, permissions.allow unioned (needs jq)
#   - the repository is then marked with .claude/clauductor-plugin, which is what makes the
#     plugin's hooks act here (hooks/if-project.sh).
#
# THE GUARD (the same as `clauductor install`'s): a repository that runs an operating model of
# its own (AGENTS.md, .claude/skills, .claude/hooks or .claude/settings.json, and no marker) is
# refused unless --force, with the list of what would be added. A repository `clauductor install`
# set up (.claude/clauductor-template) is refused outright: run one or the other, not both.
#
# Generated by `clauductor plugin build` (framework/internal/plugin/assets). Plugin @VERSION@.
set -u
PLUGIN=$(cd "$(dirname "$0")" && pwd) || exit 1
SRC="$PLUGIN/scaffold"
dry=0
force=0
for a in "$@"; do
  case $a in
    --dry-run) dry=1 ;;
    --force) force=1 ;;
    *) echo "usage: scaffold.sh [--dry-run] [--force]" >&2; exit 2 ;;
  esac
done
ROOT=$(git rev-parse --show-toplevel 2>/dev/null) || {
  echo "REFUSED: $(pwd) is not in a git repository. Run git init first (the model lives in git: branches, worktrees, PRs)." >&2
  exit 1
}
cd "$ROOT" || exit 1

if [ -f .claude/clauductor-template ]; then
  echo "REFUSED: $ROOT has the operating model from \`clauductor install\` (.claude/clauductor-template)."
  echo "Run one or the other, not both: keep the installed copy and disable the plugin for this repository"
  echo "(\"enabledPlugins\": {\"clauductor@clauductor\": false} in .claude/settings.local.json), or remove the"
  echo "installed framework files and the marker, then run /clauductor:init again."
  exit 1
fi

files=$(cd "$SRC" && find . -type f | sed 's|^\./||' | LC_ALL=C sort)
create=""
keep=""
merge=""
for f in $files; do
  case $f in
    .gitignore | CLAUDE.md | .claude/settings.json)
      if [ -e "$f" ]; then merge="$merge $f"; else create="$create $f"; fi ;;
    *)
      if [ -e "$f" ]; then keep="$keep $f"; else create="$create $f"; fi ;;
  esac
done

own=""
if [ ! -f .claude/clauductor-plugin ]; then
  for s in AGENTS.md .claude/skills .claude/hooks .claude/settings.json; do
    [ -e "$s" ] && own="$own $s"
  done
fi

list() { for x in $2; do echo "    $1 $x"; done; }
if [ -n "$own" ] && [ "$force" = 0 ]; then
  echo "REFUSED: $ROOT runs an operating model of its own (found:$own; no .claude/clauductor-plugin)."
  echo "Nothing is ever overwritten, but init would ADD these beside the project's own files:"
  list + "$create"
  [ -n "$merge" ] && { echo "and MERGE into:"; list '&' "$merge"; }
  echo "The panel needs none of this: \`clauductor panel\` works in any repository as it is. To add the"
  echo "model anyway, run again with --force (commit first)."
  exit 1
fi

echo "clauductor init in $ROOT (plugin @VERSION@)"
[ -n "$create" ] && { echo "  create:"; list + "$create"; }
[ -n "$merge" ] && { echo "  merge:"; list '&' "$merge"; }
[ -n "$keep" ] && { echo "  keep (exists, left as it is):"; list = "$keep"; }
if [ "$dry" = 1 ]; then
  echo "--dry-run: nothing written."
  exit 0
fi

for f in $create; do
  mkdir -p "$(dirname "$f")" && cp -p "$SRC/$f" "$f" || { echo "FAILED to create $f" >&2; exit 1; }
done
for f in $merge; do
  case $f in
    .gitignore)
      added=0
      while IFS= read -r line; do
        case $line in "" | "#"*) continue ;; esac
        grep -qxF -- "$line" .gitignore || { [ "$added" = 1 ] || printf '\n# clauductor\n' >> .gitignore; printf '%s\n' "$line" >> .gitignore; added=1; }
      done < "$SRC/.gitignore" ;;
    CLAUDE.md)
      grep -qxF '@AGENTS.md' CLAUDE.md || printf '\n@AGENTS.md\n' >> CLAUDE.md ;;
    .claude/settings.json)
      if command -v jq >/dev/null 2>&1 && jq -e . .claude/settings.json >/dev/null 2>&1; then
        jq -s '.[0] as $have | .[1] as $want
          | ($want * $have)
          | .permissions.allow = ((($want.permissions.allow // []) + ($have.permissions.allow // [])) | unique)' \
          .claude/settings.json "$SRC/.claude/settings.json" > .claude/settings.json.tmp &&
          mv .claude/settings.json.tmp .claude/settings.json
      else
        echo "  NOTE: .claude/settings.json kept as it is (no jq, or not valid JSON). Add by hand what"
        echo "        $SRC/.claude/settings.json sets: statusLine, permissions.allow, enabledPlugins."
      fi ;;
  esac
done
printf 'This repository runs the clauductor operating model from the clauductor plugin (@VERSION@ at init).\nThe plugin'"'"'s hooks act only where this file exists. Delete it to make them stand aside.\n' > .claude/clauductor-plugin
echo "  marked: .claude/clauductor-plugin"
echo "Next: /clauductor:start-project, then commit."
