#!/bin/sh
# SessionStart hook of the clauductor plugin.
#
# 1. Record where the loaded plugin version lives, in the plugin's persistent data directory
#    (${CLAUDE_PLUGIN_DATA}, stable across versions): `root` holds the path, and statusline.sh is a
#    shim that runs the plugin's status line. The project's statusLine command and the gate's
#    scripts/ci/clauductor-model.sh read them, because neither runs where ${CLAUDE_PLUGIN_ROOT} is
#    set and the root's path changes with every version.
# 2. Say so once when a repository has the model twice (the plugin AND `clauductor install`):
#    skills would appear twice and one of the two copies would drift.
#
# Exit 0 always: this informs, it never blocks. Generated by `clauductor plugin build`
# (framework/internal/plugin/assets).
cat >/dev/null 2>&1
root=${CLAUDE_PLUGIN_ROOT:-$(cd "$(dirname "$0")/.." && pwd)}
data=${CLAUDE_PLUGIN_DATA:-}
if [ -n "$data" ] && mkdir -p "$data" 2>/dev/null; then
  printf '%s\n' "$root" > "$data/root.tmp" && mv "$data/root.tmp" "$data/root"
  printf '#!/bin/sh\n# Written by the clauductor plugin at session start: the loaded version'"'"'s status line.\nexec sh "%s/statusline.sh" "$@"\n' "$root" > "$data/statusline.sh.tmp" &&
    mv "$data/statusline.sh.tmp" "$data/statusline.sh"
fi

proj=${CLAUDE_PROJECT_DIR:-$(git rev-parse --show-toplevel 2>/dev/null || pwd)}
note() {
  esc=$(printf '%s' "$1" | sed 's/\\/\\\\/g; s/"/\\"/g' | tr '\n\t' '  ')
  printf '{"hookSpecificOutput":{"hookEventName":"SessionStart","additionalContext":"%s"}}\n' "$esc"
}
if [ -f "$proj/.claude/clauductor-template" ]; then
  note "clauductor: this repository runs the operating model installed by \`clauductor install\` (.claude/clauductor-template), and the clauductor plugin is enabled too. The plugin's hooks stand aside here, but its /clauductor:* skills duplicate the repository's own. Use the repository's skills (/session-start, not /clauductor:session-start), and tell the owner to disable the plugin for this repository: \"enabledPlugins\": {\"clauductor@clauductor\": false} in .claude/settings.local.json."
elif [ -f "$proj/.claude/clauductor-plugin" ] && [ -f "$proj/.claude/hooks/pr-merge-guard.sh" ]; then
  note "clauductor: this repository was set up from the clauductor plugin (.claude/clauductor-plugin) but also has the model's own hooks under .claude/hooks/. Running both judges every call twice. Tell the owner: keep one (docs/plugin.md in the clauductor repository, Running both)."
fi
exit 0
