#!/bin/sh
# scaffold.sh [--dry-run] [--force] [--prune]: put the operating model's PROJECT-OWNED files into the
# current git repository, from the clauductor plugin's scaffold/ directory. The /clauductor:init
# skill runs it.
#
# The plugin carries the framework (skills, agents, hooks, the workflow, the checks). What a
# project owns and edits (AGENTS.md, .claude/project.conf, model-roles.json, docs/, changes/,
# specs/, scripts/ci/, .clauductor/panel.json, .claude/settings.json) has to live in the
# repository, so this copies it there, and NEVER overwrites a file that exists:
#   - a file that exists is kept as it is, except these four, which are merged:
#       .gitignore             missing lines appended
#       .gitattributes         missing line-ending rules PREPENDED (the project's own lines win)
#       CLAUDE.md              `@AGENTS.md` appended when absent
#       .claude/settings.json  merged as `clauductor install` merges it (needs jq): the project's
#                              keys and values kept, missing keys added, the allow/deny lists and
#                              the sandbox's excluded commands and domains unioned, the status
#                              line the plugin's
#     and settings.json's gate paths follow GATE_RUN and GATE in .claude/project.conf; a hook
#     registration that runs a .claude/hooks/ script that does not exist, or one of clauductor's
#     old model's hooks, is dropped from it (and named).
#   - .clauductor/panel.json, when created, has its lanes and branch patterns at the project's
#     BRANCH_CHANGE, BRANCH_FIX, BRANCH_OPS and MAIN_BRANCH (needs jq).
#   - the repository is then marked with .claude/clauductor-plugin, which is what makes the
#     plugin's hooks act here (hooks/if-project.sh).
#
# THE GUARD (the same as `clauductor install`'s): a repository that runs an operating model of
# its own (AGENTS.md, .claude/skills, .claude/hooks or .claude/settings.json, and no marker) is
# refused unless --force, with the list of what would be added. A repository `clauductor install`
# set up (.claude/clauductor-template) is refused outright: run one or the other, not both.
# A repository that runs clauductor's OLD model (its lock-based skills and hooks: three of its
# skills, a hook calling the binary, or settings registering one) is not refused: its old files,
# which the plugin replaces, are listed, and --prune removes them (only those; never a project file).
#
# Generated by `clauductor plugin build` (framework/internal/plugin/assets). Plugin 0.1.0.
set -u
PLUGIN=$(cd "$(dirname "$0")" && pwd) || exit 1
SRC="$PLUGIN/scaffold"
dry=0
force=0
prune=0
for a in "$@"; do
  case $a in
    --dry-run) dry=1 ;;
    --force) force=1 ;;
    --prune) prune=1 ;;
    *) echo "usage: scaffold.sh [--dry-run] [--force] [--prune]" >&2; exit 2 ;;
  esac
done
ROOT=$(git rev-parse --show-toplevel 2>/dev/null) || {
  echo "REFUSED: $(pwd) is not in a git repository. Run git init first (the model lives in git: branches, worktrees, PRs)." >&2
  exit 1
}
cd "$ROOT" || exit 1

if [ -f .claude/clauductor-template ]; then
  echo "REFUSED: $ROOT has the operating model from \`clauductor install\` (.claude/clauductor-template)."
  echo "Run one or the other, not both: keep the installed copy and disable the plugin for this repository"
  echo "(\"enabledPlugins\": {\"clauductor@clauductor\": false} in .claude/settings.local.json), or remove the"
  echo "installed framework files and the marker, then run /clauductor:init again."
  exit 1
fi

files=$(cd "$SRC" && find . -type f | sed 's|^\./||' | LC_ALL=C sort)
create=""
keep=""
merge=""
for f in $files; do
  case $f in
    .gitignore | .gitattributes | CLAUDE.md | .claude/settings.json)
      if [ -e "$f" ]; then merge="$merge $f"; else create="$create $f"; fi ;;
    *)
      if [ -e "$f" ]; then keep="$keep $f"; else create="$create $f"; fi ;;
  esac
done

# clauductor's old model (framework/internal/template/oldmodel.go holds the same lists).
OLD_SKILLS="assign blocked build claim commit done handoff milestone-complete new-milestone pane pr prd-audit release review skills spawn start-work status supervisor"
OLD_DISTINCT="assign blocked claim handoff milestone-complete new-milestone pane spawn start-work supervisor"
OLD_HOOKS="auto-lock.sh doc-freshness.sh heartbeat.sh lock-guard.sh session-register.sh status-sync.sh"
old_files=""
for x in $OLD_SKILLS; do [ -f ".claude/skills/$x/SKILL.md" ] && old_files="$old_files .claude/skills/$x/SKILL.md"; done
for x in $OLD_HOOKS; do [ -f ".claude/hooks/$x" ] && old_files="$old_files .claude/hooks/$x"; done
old_model=0
n=0; for x in $OLD_DISTINCT; do [ -f ".claude/skills/$x/SKILL.md" ] && n=$((n + 1)); done
[ "$n" -ge 3 ] && old_model=1
for x in $OLD_HOOKS; do grep -qs 'clauductor ' ".claude/hooks/$x" && old_model=1; done
for x in $OLD_HOOKS; do grep -qs "\.claude/hooks/$x" .claude/settings.json && old_model=1; done
[ -f orchestration/config.json ] && old_model=1

own=""
if [ ! -f .claude/clauductor-plugin ] && [ "$old_model" = 0 ]; then
  for s in AGENTS.md .claude/skills .claude/hooks .claude/settings.json; do
    [ -e "$s" ] && own="$own $s"
  done
fi

list() { for x in $2; do echo "    $1 $x"; done; }
if [ -n "$own" ] && [ "$force" = 0 ]; then
  echo "REFUSED: $ROOT runs an operating model of its own (found:$own; no .claude/clauductor-plugin)."
  echo "Nothing is ever overwritten, but init would ADD these beside the project's own files:"
  list + "$create"
  [ -n "$merge" ] && { echo "and MERGE into:"; list '&' "$merge"; }
  echo "The panel needs none of this: \`clauductor panel\` works in any repository as it is. To add the"
  echo "model anyway, run again with --force (commit first)."
  exit 1
fi

echo "clauductor init in $ROOT (plugin 0.1.0)"
[ -n "$create" ] && { echo "  create:"; list + "$create"; }
[ -n "$merge" ] && { echo "  merge:"; list '&' "$merge"; }
[ -n "$keep" ] && { echo "  keep (exists, left as it is):"; list = "$keep"; }
if [ -n "$old_files" ]; then
  echo "  OLD MODEL: clauductor's old operating model runs here; the plugin replaces these files:"
  list - "$old_files"
  if [ "$prune" = 1 ]; then echo "  --prune: they will be removed (nothing else is)."
  else echo "  Kept. Run again with --prune to remove them (only them; never a project file)."; fi
fi
if [ "$dry" = 1 ]; then
  echo "--dry-run: nothing written."
  exit 0
fi

for f in $create; do
  mkdir -p "$(dirname "$f")" && cp -p "$SRC/$f" "$f" || { echo "FAILED to create $f" >&2; exit 1; }
done

# render_settings: the scaffold's settings.json with the gate's paths (allow rules, sandbox
# exclusions) at the project's GATE_RUN and GATE, read from its project.conf in a subshell.
conf_get() { sh -c '[ -f .claude/project.conf ] && . ./.claude/project.conf >/dev/null 2>&1; eval "printf %s \"\${$1:-$2}\""' _ "$1" "$2"; }
render_settings() {
  if command -v jq >/dev/null 2>&1; then
    jq --arg r "$(conf_get GATE_RUN scripts/ci/run-local.sh)" --arg g "$(conf_get GATE scripts/ci/gate.sh)" '
      def rp: if type == "string" then (split("scripts/ci/run-local.sh") | join($r)) | (split("scripts/ci/gate.sh") | join($g)) else . end;
      (if .permissions.allow then .permissions.allow |= map(rp) else . end)
      | (if .sandbox.excludedCommands then .sandbox.excludedCommands |= map(rp) else . end)' "$SRC/.claude/settings.json"
  else
    cat "$SRC/.claude/settings.json"
  fi
}
case " $create " in
  *" .claude/settings.json "*) render_settings > .claude/settings.json.tmp && mv .claude/settings.json.tmp .claude/settings.json ;;
esac
# The panel preset with the project's branch keys (unchanged when it keeps the defaults).
case " $create " in
  *" .clauductor/panel.json "*)
    c=$(conf_get BRANCH_CHANGE change/) f=$(conf_get BRANCH_FIX fix/) o=$(conf_get BRANCH_OPS ops/) m=$(conf_get MAIN_BRANCH main)
    if [ "$c$f$o$m" != "change/fix/ops/main" ]; then
      if command -v jq >/dev/null 2>&1; then
        jq --arg c "$c" --arg f "$f" --arg o "$o" --arg m "$m" '
          {"change/": $c, "fix/": $f, "ops/": $o, "main": $m} as $pre
          | .lanes |= with_entries(.key = ($pre[.key] // .key))
          | .templates |= map(if .branch_pattern then .branch_pattern |= (. as $b
              | ([("change/", "fix/", "ops/") | select(. as $p | $b | startswith($p))] | first) as $p
              | if $p then $pre[$p] + ($b | ltrimstr($p)) else $b end) else . end)' \
          .clauductor/panel.json > .clauductor/panel.json.tmp && mv .clauductor/panel.json.tmp .clauductor/panel.json
      else
        echo "  NOTE: .clauductor/panel.json uses the default branch prefixes (no jq): set its lanes and branch patterns to $c, $f, $o."
      fi
    fi ;;
esac
# Hook registrations that would run a script that does not exist, or the old model's hooks.
if [ -f .claude/settings.json ] && command -v jq >/dev/null 2>&1; then
  dead=""
  for h in $(grep -o '\.claude/hooks/[A-Za-z0-9_.-]*\.sh' .claude/settings.json | LC_ALL=C sort -u); do
    x=${h##*/}
    case " $OLD_HOOKS " in *" $x "*) dead="$dead $x"; continue ;; esac
    [ -f "$h" ] || dead="$dead $x"
  done
  if [ -n "$dead" ]; then
    jq --arg dead "$dead" '
      ($dead | split(" ") | map(select(. != ""))) as $d
      | def live: (.command // "") as $c | ($d | any(. as $x | $c | contains(".claude/hooks/" + $x))) | not;
      if .hooks then .hooks |= (with_entries(.value |= (map(if .hooks then .hooks |= map(select(live)) else . end) | map(select((.hooks // [1]) | length > 0))))
                                | with_entries(select(.value | length > 0))) else . end' \
      .claude/settings.json > .claude/settings.json.tmp && mv .claude/settings.json.tmp .claude/settings.json
    for x in $dead; do echo "  settings.json: dropped the hook registration running .claude/hooks/$x (missing, or the old model's)"; done
  fi
fi
if [ "$prune" = 1 ] && [ -n "$old_files" ]; then
  for f in $old_files; do
    rm -f "$f" && echo "  removed $f"
    case $f in .claude/skills/*) rmdir "$(dirname "$f")" 2>/dev/null ;; esac
  done
fi
for f in $merge; do
  case $f in
    .gitignore)
      added=0
      while IFS= read -r line; do
        case $line in "" | "#"*) continue ;; esac
        grep -qxF -- "$line" .gitignore || { [ "$added" = 1 ] || printf '\n# clauductor\n' >> .gitignore; printf '%s\n' "$line" >> .gitignore; added=1; }
      done < "$SRC/.gitignore" ;;
    .gitattributes)
      # PREPENDED, not appended: the last matching line wins, so the project's own lines must
      # stay after the catch-all `* text=auto eol=lf` to keep overriding it.
      # Lines compare trimmed, CR included, as `clauductor install` compares them: a CRLF file or
      # a trailing space must not read as a missing rule and add it twice.
      trim() { tr -d '\r' | sed 's/^[[:space:]]*//; s/[[:space:]]*$//'; }
      have=$(trim < .gitattributes)
      missing=""
      while IFS= read -r line; do
        line=$(printf '%s' "$line" | trim)
        case $line in "" | "#"*) continue ;; esac
        printf '%s\n' "$have" | grep -qxF -- "$line" || missing="$missing$line
"
      done < "$SRC/.gitattributes"
      if [ -n "$missing" ]; then
        { printf '# Clauductor: LF line endings on every OS, so shell scripts run under WSL2 and Git for Windows\n'
          printf '# (.claude/checks/line-endings.sh holds it). Your own lines below still override these.\n%s\n' "$missing"
          cat .gitattributes; } > .gitattributes.tmp && mv .gitattributes.tmp .gitattributes
      fi ;;
    CLAUDE.md)
      grep -qxF '@AGENTS.md' CLAUDE.md || printf '\n@AGENTS.md\n' >> CLAUDE.md ;;
    .claude/settings.json)
      if command -v jq >/dev/null 2>&1 && jq -e . .claude/settings.json >/dev/null 2>&1; then
        render_settings > .claude/settings.json.want &&
        jq -s '.[0] as $have | .[1] as $want
          | def u($a; $b): ($a // []) + (($b // []) - ($a // []));
          ($want * $have)
          | .statusLine = $want.statusLine
          | .permissions.allow = u($have.permissions.allow; $want.permissions.allow)
          | .permissions.deny = u($have.permissions.deny; $want.permissions.deny)
          | .sandbox.excludedCommands = u($have.sandbox.excludedCommands; $want.sandbox.excludedCommands)
          | .sandbox.network.allowedDomains = u($have.sandbox.network.allowedDomains; $want.sandbox.network.allowedDomains)' \
          .claude/settings.json .claude/settings.json.want > .claude/settings.json.tmp &&
          mv .claude/settings.json.tmp .claude/settings.json
        rm -f .claude/settings.json.want
      else
        echo "  NOTE: .claude/settings.json kept as it is (no jq, or not valid JSON). Add by hand what"
        echo "        $SRC/.claude/settings.json sets: statusLine, permissions.allow, enabledPlugins."
      fi ;;
  esac
done
printf 'This repository runs the clauductor operating model from the clauductor plugin (0.1.0 at init).\nThe plugin'"'"'s hooks act only where this file exists. Delete it to make them stand aside.\n' > .claude/clauductor-plugin
echo "  marked: .claude/clauductor-plugin"
echo "Next: /clauductor:start-project, then commit."
