#!/bin/sh
# if-project.sh HOOK: run one of the operating model's hooks, but only in a repository that runs
# the model FROM THIS PLUGIN.
#
# WHY. An installed plugin's hooks fire in every repository the user opens, and these hooks
# enforce one project's rules (no auto-merge, no scripted rewrites of tracked source). They apply
# where /clauductor:init set the model up, marked by .claude/clauductor-plugin, and nowhere else.
# A repository where `clauductor install` put the model (.claude/clauductor-template) registers
# its own copies of the same hooks in its settings.json; running the plugin's too would judge
# every call twice, so the plugin stands aside there.
#
# Standing aside is exit 0 with the payload unread: allow, silently. Generated by
# `clauductor plugin build` (framework/internal/plugin/assets).
hook=${1:?usage: if-project.sh <hook>.sh}
dir=$(cd "$(dirname "$0")" && pwd)
proj=${CLAUDE_PROJECT_DIR:-$(git rev-parse --show-toplevel 2>/dev/null || pwd)}
[ -f "$proj/.claude/clauductor-plugin" ] || exit 0
[ -f "$proj/.claude/clauductor-template" ] && exit 0
exec sh "$dir/$hook"
